  var paises = [
      ['Afganistán', '4'],
      ['Åland', '248'],
      ['Albania', '8'],
      ['Alemania', '276'],
      ['Andorra', '20'],
      ['Angola', '24'],
      ['Anguila', '660'],
      ['Antártida', '10'],
      ['Antigua y Barbuda', '28'],
      ['Arabia Saudita', '682'],
      ['Argelia', '12'],
      ['Argentina', '32'],
      ['Armenia', '51'],
      ['Aruba', '533'],
      ['Australia', '36'],
      ['Austria', '40'],
      ['Azerbaiyán', '31'],
      ['Bahamas', '44'],
      ['Bangladés', '50'],
      ['Barbados', '52'],
      ['Baréin', '48'],
      ['Bélgica', '56'],
      ['Belice', '84'],
      ['Benín', '204'],
      ['Bermudas', '60'],
      ['Bielorrusia', '112'],
      ['Bolivia', '68'],
      ['Bonaire, San Eustaquio y Saba', '535'],
      ['Bosnia y Herzegovina', '70'],
      ['Botsuana', '72'],
      ['Brasil', '76'],
      ['Brunéi', '96'],
      ['Bulgaria', '100'],
      ['Burkina Faso', '854'],
      ['Burundi', '108'],
      ['Bután', '64'],
      ['Cabo Verde', '132'],
      ['Camboya', '116'],
      ['Camerún', '120'],
      ['Canadá', '124'],
      ['Catar', '634'],
      ['Chad', '148'],
      ['Chile', '152'],
      ['China', '156'],
      ['Chipre', '196'],
      ['Colombia', '170'],
      ['Comoras', '174'],
      ['Corea del Norte', '408'],
      ['Corea del Sur', '410'],
      ['Costa de Marfil', '384'],
      ['Costa Rica', '188'],
      ['Croacia', '191'],
      ['Cuba', '192'],
      ['Curazao', '531'],
      ['Dinamarca', '208'],
      ['Dominica', '212'],
      ['Ecuador', '218'],
      ['Egipto', '818'],
      ['El Salvador', '222'],
      ['Emiratos Árabes Unidos', '784'],
      ['Eritrea', '232'],
      ['Eslovaquia', '703'],
      ['Eslovenia', '705'],
      ['España', '724'],
      ['Estados Unidos', '840'],
      ['Estonia', '233'],
      ['Etiopía', '231'],
      ['Filipinas', '608'],
      ['Finlandia', '246'],
      ['Fiyi', '242'],
      ['Francia', '250'],
      ['Gabón', '266'],
      ['Gambia', '270'],
      ['Georgia', '268'],
      ['Ghana', '288'],
      ['Gibraltar', '292'],
      ['Granada', '308'],
      ['Grecia', '300'],
      ['Groenlandia', '304'],
      ['Guadalupe', '312'],
      ['Guam', '316'],
      ['Guatemala', '320'],
      ['Guayana Francesa', '254'],
      ['Guernsey', '831'],
      ['Guinea', '324'],
      ['Guinea-Bisáu', '624'],
      ['Guinea Ecuatorial', '226'],
      ['Guyana', '328'],
      ['Haití', '332'],
      ['Honduras', '340'],
      ['Hong Kong', '344'],
      ['Hungría', '348'],
      ['India', '356'],
      ['Indonesia', '360'],
      ['Irak', '368'],
      ['Irán', '364'],
      ['Irlanda', '372'],
      ['Isla Bouvet', '74'],
      ['Isla de Man', '833'],
      ['Isla de Navidad', '162'],
      ['Islandia', '352'],
      ['Islas Caimán', '136'],
      ['Islas Cocos', '166'],
      ['Islas Cook', '184'],
      ['Islas Feroe', '234'],
      ['Islas Georgias del Sur y Sandwich del Sur', '239'],
      ['Islas Heard y McDonald', '334'],
      ['Islas Malvinas', '238'],
      ['Islas Marianas del Norte', '580'],
      ['Islas Marshall', '584'],
      ['Islas Pitcairn', '612'],
      ['Islas Salomón', '90'],
      ['Islas Turcas y Caicos', '796'],
      ['Islas ultramarinas de Estados Unidos', '581'],
      ['Islas Vírgenes Británicas', '92'],
      ['Islas Vírgenes de los Estados Unidos', '850'],
      ['Israel', '376'],
      ['Italia', '380'],
      ['Jamaica', '388'],
      ['Japón', '392'],
      ['Jersey', '832'],
      ['Jordania', '400'],
      ['Kazajistán', '398'],
      ['Kenia', '404'],
      ['Kirguistán', '417'],
      ['Kiribati', '296'],
      ['Kuwait', '414'],
      ['Laos', '418'],
      ['Lesoto', '426'],
      ['Letonia', '428'],
      ['Líbano', '422'],
      ['Liberia', '430'],
      ['Libia', '434'],
      ['Liechtenstein', '438'],
      ['Lituania', '440'],
      ['Luxemburgo', '442'],
      ['Macao', '446'],
      ['Macedonia', '807'],
      ['Madagascar', '450'],
      ['Malasia', '458'],
      ['Malaui', '454'],
      ['Maldivas', '462'],
      ['Malí', '466'],
      ['Malta', '470'],
      ['Marruecos', '504'],
      ['Martinica', '474'],
      ['Mauricio', '480'],
      ['Mauritania', '478'],
      ['Mayotte', '175'],
      ['México', '484'],
      ['Micronesia', '583'],
      ['Moldavia', '498'],
      ['Mónaco', '492'],
      ['Mongolia', '496'],
      ['Montenegro', '499'],
      ['Montserrat', '500'],
      ['Mozambique', '508'],
      ['Myanmar', '104'],
      ['Namibia', '516'],
      ['Nauru', '520'],
      ['Nepal', '524'],
      ['Nicaragua', '558'],
      ['Níger', '562'],
      ['Nigeria', '566'],
      ['Niue', '570'],
      ['Norfolk', '574'],
      ['Noruega', '578'],
      ['Nueva Caledonia', '540'],
      ['Nueva Zelanda', '554'],
      ['Omán', '512'],
      ['Países Bajos', '528'],
      ['Pakistán', '586'],
      ['Palaos', '585'],
      ['Palestina', '275'],
      ['Panamá', '591'],
      ['Papúa Nueva Guinea', '598'],
      ['Paraguay', '600'],
      ['Perú', '604'],
      ['Polinesia Francesa', '258'],
      ['Polonia', '616'],
      ['Portugal', '620'],
      ['Puerto Rico', '630'],
      ['Reino Unido', '826'],
      ['República Árabe Saharaui Democrática', '732'],
      ['República Centroafricana', '140'],
      ['República Checa', '203'],
      ['República del Congo', '178'],
      ['República Democrática del Congo', '180'],
      ['República Dominicana', '214'],
      ['Reunión', '638'],
      ['Ruanda', '646'],
      ['Rumania', '642'],
      ['Rusia', '643'],
      ['Samoa', '882'],
      ['Samoa Americana', '16'],
      ['San Bartolomé', '652'],
      ['San Cristóbal y Nieves', '659'],
      ['San Marino', '674'],
      ['San Martín', '663'],
      ['San Pedro y Miquelón', '666'],
      ['San Vicente y las Granadinas', '670'],
      ['Santa Elena, Ascensión y Tristán de Acuña', '654'],
      ['Santa Lucía', '662'],
      ['Santo Tomé y Príncipe', '678'],
      ['Senegal', '686'],
      ['Serbia', '688'],
      ['Seychelles', '690'],
      ['Sierra Leona', '694'],
      ['Singapur', '702'],
      ['Sint Maarten', '534'],
      ['Siria', '760'],
      ['Somalia', '706'],
      ['Sri Lanka', '144'],
      ['Suazilandia', '748'],
      ['Sudáfrica', '710'],
      ['Sudán', '729'],
      ['Sudán del Sur', '728'],
      ['Suecia', '752'],
      ['Suiza', '756'],
      ['Surinam', '740'],
      ['Svalbard y Jan Mayen', '744'],
      ['Tailandia', '764'],
      ['Taiwán (República de China)', '158'],
      ['Tanzania', '834'],
      ['Tayikistán', '762'],
      ['Territorio Británico del Océano Índico', '86'],
      ['Tierras Australes y Antárticas Francesas', '260'],
      ['Timor Oriental', '626'],
      ['Togo', '768'],
      ['Tokelau', '772'],
      ['Tonga', '776'],
      ['Trinidad y Tobago', '780'],
      ['Túnez', '788'],
      ['Turkmenistán', '795'],
      ['Turquía', '792'],
      ['Tuvalu', '798'],
      ['Ucrania', '804'],
      ['Uganda', '800'],
      ['Uruguay', '858'],
      ['Uzbekistán', '860'],
      ['Vanuatu', '548'],
      ['Vaticano, Ciudad del', '336'],
      ['Venezuela', '862'],
      ['Vietnam', '704'],
      ['Wallis y Futuna', '876'],
      ['Yemen', '887'],
      ['Yibuti', '262'],
      ['Zambia', '894'],
      ['Zimbabue', '716']
  ];
